//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://svcs.paypal.com/types/ap")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://svcs.paypal.com/types/ap", IsNullable=false)]
public partial class RefundResponse {
    
    private string currencyCodeField;
    
    private RefundResponseResponseEnvelope responseEnvelopeField;
    
    private RefundResponseRefundInfo[] refundInfoListField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string currencyCode {
        get {
            return this.currencyCodeField;
        }
        set {
            this.currencyCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RefundResponseResponseEnvelope responseEnvelope {
        get {
            return this.responseEnvelopeField;
        }
        set {
            this.responseEnvelopeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("refundInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public RefundResponseRefundInfo[] refundInfoList {
        get {
            return this.refundInfoListField;
        }
        set {
            this.refundInfoListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://svcs.paypal.com/types/ap")]
public partial class RefundResponseResponseEnvelope {
    
    private string timestampField;
    
    private string ackField;
    
    private string correlationIdField;
    
    private string buildField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ack {
        get {
            return this.ackField;
        }
        set {
            this.ackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string correlationId {
        get {
            return this.correlationIdField;
        }
        set {
            this.correlationIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string build {
        get {
            return this.buildField;
        }
        set {
            this.buildField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://svcs.paypal.com/types/ap")]
public partial class RefundResponseRefundInfo {
    
    private string refundStatusField;
    
    private string refundHasBecomeFullField;
    
    private RefundResponseRefundInfoReceiver[] receiverField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string refundStatus {
        get {
            return this.refundStatusField;
        }
        set {
            this.refundStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string refundHasBecomeFull {
        get {
            return this.refundHasBecomeFullField;
        }
        set {
            this.refundHasBecomeFullField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("receiver", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RefundResponseRefundInfoReceiver[] receiver {
        get {
            return this.receiverField;
        }
        set {
            this.receiverField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://svcs.paypal.com/types/ap")]
public partial class RefundResponseRefundInfoReceiver {
    
    private string amountField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://svcs.paypal.com/types/ap")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://svcs.paypal.com/types/ap", IsNullable=false)]
public partial class NewDataSet {
    
    private RefundResponse[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RefundResponse")]
    public RefundResponse[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
